apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>Privet</h1>
    </br>
    <h1>I have succeeded in the assignment</h1>
    </html